version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Logging into ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 586928288932.dkr.ecr.us-east-1.amazonaws.com

  pre_build:
    commands:
      - echo Building Spring Boot JAR...
      - mvn clean package -DskipTests
      - echo JAR build complete

  build:
    commands:
      - IMAGE_REPO=586928288932.dkr.ecr.us-east-1.amazonaws.com/awspringbootdeployment-app
      - IMAGE_TAG=latest
      - echo Building Docker image...
      - docker build -t $IMAGE_REPO:$IMAGE_TAG .
      - echo Pushing Docker image...
      - docker push $IMAGE_REPO:$IMAGE_TAG

artifacts:
  files:
    - target/*.jar
