version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    IMAGE_REPO_NAME: "awspringbootdeployment-app"
    AWS_ACCOUNT_ID: "586928288932"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - 'echo Installing prerequisites'
      - 'echo Logging into ECR'
      - 'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com'

  pre_build:
    commands:
      - 'echo Preparing build environment'
      - 'echo Source version: $CODEBUILD_RESOLVED_SOURCE_VERSION'

  build:
    commands:
      - 'echo Building Spring Boot JAR'
      - 'set -o pipefail'
      - 'mvn -X clean package -DskipTests | tee build.log'

      - 'echo Packaging complete, status: $?'  # shows mvn exit code
      - 'echo Building Docker image'
      - 'IMAGE_TAG=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION'
      - 'docker build -t $IMAGE_TAG .'
      - 'docker push $IMAGE_TAG'

  post_build:
    commands:
      - 'echo Build completed on $(date)'
      - 'echo Image URI: $IMAGE_TAG'
      - 'export IMAGE_URI=$IMAGE_TAG'

artifacts:
  files:
    - target/*.jar
    - build.log
  discard-paths: yes
