version: 0.2
phases:
  build:
    commands:
      - set -euo pipefail
      - echo "Creating imagedefinitions.json (static)…"
      - cat > imagedefinitions.json <<'JSON'
[
  {"name":"springboot-ecs-new","imageUri":"586928288932.dkr.ecr.us-east-1.amazonaws.com/awspringbootdeployment-app:latest"}
]
JSON
      - echo "Validating JSON with Python…"
      - python3 - <<'PY'
import json, io
json.load(io.open("imagedefinitions.json","r",encoding="utf-8"))
print("JSON is valid")
PY
      - echo "Workspace listing:" && pwd && ls -la && echo "-----"; cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes
