version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    IMAGE_REPO_NAME: "awspringbootdeployment-app"
    AWS_ACCOUNT_ID: "586928288932"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - 'echo Installing prerequisites'
      - 'echo Logging into ECR'
      - 'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com'

  pre_build:
    commands:
      - 'echo Preparing build environment'
      - 'echo CodeBuild source version: $CODEBUILD_RESOLVED_SOURCE_VERSION'

  build:
    commands:
      - 'echo Building Spring Boot JAR'
      - 'mvn clean package -DskipTests'
      - 'echo Packaging complete'
      - 'IMAGE_TAG=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION'
      - 'echo Building Docker image: $IMAGE_TAG'
      - 'docker build -t $IMAGE_TAG .'
      - 'echo Pushing Docker image to ECR'
      - 'docker push $IMAGE_TAG'

  post_build:
    commands:
      - 'echo Build completed on $(date)'
      - 'echo Exporting IMAGE_URI'
      - 'export IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION'

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
