version: 0.2
phases:
  build:
    commands:
      - 'echo creating imagedefinitions.json'
      - 'printf "[{\\"name\\":\\"springboot-ecs-new\\",\\"imageUri\\":\\"586928288932.dkr.ecr.us-east-1.amazonaws.com/awspringbootdeployment-app:latest\\"}]\n" > imagedefinitions.json'
      - 'echo WORKDIR: $(pwd) && ls -la'
      - 'echo CONTENTS:'
      - 'cat imagedefinitions.json'
artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes
