version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using Java Corretto 17"
      - echo "Logging into ECR account 1..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 581573371430.dkr.ecr.us-east-1.amazonaws.com
      - echo "Logging into ECR account 2..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 586928288932.dkr.ecr.us-east-1.amazonaws.com

  pre_build:
    commands:
      - echo "Building Spring Boot JAR..."
      - mvn clean package -DskipTests
      - echo "JAR build complete"

  build:
    commands:
      - echo "Setting IMAGE_TAG and building Docker image..."
      - IMAGE_TAG=586928288932.dkr.ecr.us-east-1.amazonaws.com/awspringbootdeployment-app:$CODEBUILD_RESOLVED_SOURCE_VERSION && \
        docker build -t $IMAGE_TAG . && \
        echo "Pushing image to ECR..." && \
        docker push $IMAGE_TAG

artifacts:
  files:
    - target/*.jar
