version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 657880976613.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 657880976613.dkr.ecr.us-east-2.amazonaws.com/springboot-inventory-app:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - echo Pushing the Docker image to ECR...
      - docker push 657880976613.dkr.ecr.us-east-2.amazonaws.com/springboot-inventory-app:$CODEBUILD_RESOLVED_SOURCE_VERSION
artifacts:
  files:
    - '**/*'
