version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    IMAGE_REPO_NAME: "awspringbootdeployment-app"
    AWS_ACCOUNT_ID: "586928288932"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - 'echo Using Java Corretto 11'
      - 'echo Logging into ECR...'
      - 'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com'

  pre_build:
    commands:
      - 'echo Building Spring Boot JAR...'
      - 'mvn -X clean package -DskipTests > build.log 2>&1 || true'
      - 'echo ---- MAVEN BUILD LOG ----'
      - 'tail -n 100 build.log'
      - |
        if grep -q "\[ERROR\]" build.log; then
          echo "BUILD FAILED"
          cat build.log
          exit 1
        fi
      - 'echo JAR build complete'

  build:
    commands:
      - 'IMAGE_TAG=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION'
      - 'echo Building Docker image: $IMAGE_TAG'
      - 'docker build -t $IMAGE_TAG .'
      - 'echo Pushing image to ECR...'
      - 'docker push $IMAGE_TAG'

  post_build:
    commands:
      - 'echo Build completed on `date`'
      - 'echo Image URI: $IMAGE_TAG'
      - 'export IMAGE_URI=$IMAGE_TAG'

artifacts:
  files:
    - target/*.jar
    - build.log
    - target/surefire-reports/**/*
  discard-paths: yes

reports:
  build_report:
    files:
      - 'target/surefire-reports/*.txt'
    base-directory: 'target/surefire-reports'
    discard-paths: yes
